### ISSUE TITLE
Great Post!

### ISSUE THREAD

**Issue by zbruhnke** [woodruffw/blog#1]
https://github.com/woodruffw/blog/blob/master/_posts/2019-12-25-A-shallow-dive-into-the-American-banking-system.md

Really enjoyed reading this - I can read and noticed you are not currently responding to recruiters or looking for employment, however if you ever want to come hack on banking with us at HMBradley I think it's fair to say your personality would fit in well with us!

We're a team of FinTech Nerds re-thinking the way banking works for a more modern era and we go deep down rabbit holes to find answers to questions that seemingly no one is asking.

In any case, keep up the good writing I'll be following along from here on out for sure.

Sorry for the strange way of reaching out but this felt more genuine than just spamming you with some recruiting email. :)

-Best
Zach

**Comment by woodruffw** [comment]
Thanks for the kind words! Do stay tuned; I plan to do some follow-up posts on more ACH details ;)

And yes, I'm not currently looking for employment. But thank you for extending the offer, and best of luck with your endeavours!
